### ISSUE TITLE
Would you consider adding Conan support to the main PcapPlusPlus branch? 

### ISSUE THREAD

**Issue by seladb** [AndreyBronin/conan-PcapPlusPlus#2]

**Comment by AndreyBronin** [comment]
It would be nice, I'll send You pull request soon

**Comment by seladb** [comment]
Sure, that would be awesome, thanks!

**Comment by seladb** [comment]
With a great help from the [Bincrafters team](https://bincrafters.github.io/) I added a Conan recipe for PcapPlusPlus on Windows, Linux and MacOS, please feel free to check it out: https://github.com/bincrafters/conan-pcapplusplus

Repo on Bintray: https://bintray.com/bincrafters/public-conan/pcapplusplus%3Abincrafters
